set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_text "#{b:pane_current_path}"
set -g @catppuccin_window_current_text "#{b:pane_current_path}"
set -g @catppuccin_window_text_color "#{@thm_surface_0}"
set -g @catppuccin_window_current_text_color "#{@thm_surface_0}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_fill "all"

set -g @catppuccin_status_background "none"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g status-left ""

# Bell: red number when bell fires, otherwise default colors
set -g @catppuccin_window_number_color "#{?window_bell_flag,#{@thm_red},#{@thm_overlay_1}}"

